version: '3'

services:
    mainserver:
        image: oadrianoo/weex-backend/mainserver
        build:
          context: .
          args:
            ENV: production
        ports:
          - "5001:5001"
        restart: always
        env_file: ./.env      