version: '3'

services:
    mainserver:
        image: oadrianoo/weex-backend/mainserver
        build: .
        ports:
          - "5001:5001"
        restart: always
        env_file: ./.env      