version: '2'

services:
  api:
    image: node-api
    build:
      context: .      
    env_file: ./.env
    ports:
      - "3001:3001"
      - "5001:5001"
  db:
    image: mysql:8.0
    restart: always
    ports: 
      - "3306:3306"
    env_file: ./.env
    


